#!/bin/bash

# run a command from the root of the current git repository

GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)

if [ $? -eq '0' ]; then
    cd "$GIT_ROOT"
    $@
    exit $?
else
    printf "not in a git repo\n" 1>&2
    exit 1
fi
