#!/usr/bin/perl

use strict;
use warnings;
use v5.16.3;
use autodie;

my $arg = $ARGV[0];

unless ($arg && $arg =~ /^(?:debug|normal)$/) {
    die "expected arg 'debug' or 'normal'\n";
}

my $compile_cmd = 'make clean; make -j4 SOURCES=sega NOWERROR=1 REGENIE=1 ARCHOPTS=-U_FORTIFY_SOURCE';
$compile_cmd   .= ' OPTIMIZE=0 SYMBOLS=1 SYMLEVEL=3' if $arg eq 'debug';

my $mame_dir = '/home/_73/p/emus/mame';

chdir $mame_dir;

if (0 == system($compile_cmd)) {
    rename './mame', './mame-debug' if $arg eq 'debug';
}

exit $?;
