#!/usr/bin/perl

use strict;
use warnings;
use v5.16.3;
use autodie;

# mame leaves files around in the working dir, how annoying ...

chdir "$ENV{HOME}/p/emus/mame";
exit(system($ARGV[0] eq 'debug' ? './mame-debug' : './mame'))
