#!/usr/bin/perl

use strict;
use warnings;
use v5.16.3;
use autodie;

my $arg = $ARGV[0];

unless (@ARGV == 1 && $arg && $arg =~ /^(?:debug|optimize)$/) {
    die "_mame-compile: expected one arg 'debug' or 'optimize'\n";
}

my $compile_cmd = 'make -j4 SOURCES=sega NOWERROR=1 REGENIE=1 ARCHOPTS=-U_FORTIFY_SOURCE';
$compile_cmd   .= ' OPTIMIZE=0 SYMBOLS=1 SYMLEVEL=3' if $arg eq 'debug';

my $mame_dir = '/home/_73/p/mame';

chdir $mame_dir;

if (0 == system($compile_cmd)) {
    if ($arg eq 'debug') { rename './mame', './mame-debug'    }
    else                 { rename './mame', './mame-optimize' }
}

exit $?;
