#!/usr/bin/perl

use strict;
use warnings;
use v5.16;

my $usage = 'usage: _megamu [optimize|debug] MEGAMU_ARGS';
my $arg = shift @ARGV;
die "$usage\n" unless $arg and $arg =~ /^(optimize|debug)$/;
my $exe = $arg eq 'debug' ? 'megamu-debug' : 'megamu-optimize';
exit(system "$ENV{HOME}/p/MegaMu/MegaMu/build/$exe", @ARGV);
