#!/bin/bash

cleanup_and_exit() {
    rm -rf /tmp/ovn-sync-workspace
    exit 12
}
trap cleanup_and_exit INT TERM
~/p/ovn-sync/ovn_sync.py --keep-workspace --ovn22.03 distgit_sync --no-push
diff -r --exclude='*.git' ~/p/ovn-sync/ovn-sync-workspace /tmp/ovn-sync-workspace
ret=$?
rm -rf /tmp/ovn-sync-workspace
