#!/bin/bash

if [[ $(id -u) != 0 ]]; then
  echo "$0: must be root user" >&2
  exit 1
fi

OVN_SRC_PATH=${OVN_SRC_PATH:-~nhubbard/p/ovn}
OVS_SRC_PATH=${OVS_SRC_PATH:-$OVN_SRC_PATH/ovs}
OVN_FAKE_MULTINODE_PATH=${OVN_FAKE_MULTINODE_PATH:-~nhubbard/p/ovn-fake-multinode}

cd $OVN_FAKE_MULTINODE_PATH

set -x

./ovn_cluster.sh stop
podman rmi -f ovn/ovn-multi-node
podman rmi -f ovn/cinc
podman system prune --all -f
OVN_CFLAGS='-g3 -fno-omit-frame-pointer -fPIC' OVN_SRC_PATH="$OVN_SRC_PATH" OVS_SRC_PATH="$OVS_SRC_PATH" ./ovn_cluster.sh build
./ovn_cluster.sh start
