#!/bin/bash

tstamp=$(date "+%Y%m%d-%H%M%S")
TEED_DIR=$HOME/cmds
TEED_NAME="$@ $tstamp"

if ! [[ -d $TEED_DIR ]]; then
    mkdir -p $TEED_DIR
fi

set -o pipefail
( $@ ) |& tee "$TEED_DIR/$TEED_NAME"
exit $?
