#!/bin/bash

tstamp=$(date "+%Y%m%d-%H%M%S")
tee_dir=$HOME/cmds
tee_name=$(printf "%q" "$* $tstamp" | tr / '\\')

if ! [ -d $tee_dir ]; then
    mkdir -p $tee_dir
fi

set -o pipefail
$@ |& tee "$tee_dir/$tee_name"
exit $?
