#!/bin/bash

# For some reason my touchpad occasionally stops working and I need to reload
# the psmouse kernel module.

SCRIPT=${0##*/}

if [[ $(id -u) != 0 ]]; then
    echo "$SCRIPT: must be run by the root user. Exiting." >&2
    exit 1
fi

rmmod psmouse
modprobe psmouse
