#!/bin/sh

# Until I figure out how to reliably find the current screen width, just abuse
# that xdotool handles an unreasonably large input by deafulting to the max
# width. The shortest path between two points is a straight line.
xdotool mousemove 1000000 0
