#!/bin/bash

# Install a package from SlackBuilds.org using sbopkg(8) and sqg(8).

set -e

SCRIPT=${0##*/}

USAGE="Usage: $SCRIPT <packagename(s)>"
if [ "$1" = '--help' ] || [ "$1" = '-h' ]; then
  echo "$USAGE"
  exit 0;
fi

if [[ $(id -u) != 0 ]]; then
    echo "$SCRIPT: $SCRIPT must be run by the root user. Exiting." >&2
    exit 1
fi

sboupdate_command='sbopkg -r'
echo "$SCRIPT: Executing: $sboupdate_command"
eval "$sboupdate_command"

for package in "$@"; do
  queuefile="$package-$SCRIPT"
  sqg_command="sqg -p $package -o $queuefile"
  echo "$SCRIPT: Executing: $sqg_command"
  eval "$sqg_command"
  if [ -n "$QUEUEFILES" ]; then
    QUEUEFILES="$QUEUEFILES $queuefile"
  else
    QUEUEFILES="$queuefile"
  fi
done

sbopkg_command="sbopkg -i $QUEUEFILES"
echo "$SCRIPT: Executing: $sbopkg_command"
eval "$sbopkg_command"
